In [272]:
import pandas as pd
import numpy as np
import re

In [273]:
df = pd.read_csv(r"audible_uncleaned.csv")
df

,name,author,narrator,time,releasedate,language,stars,price
0,Geronimo Stilton #11 & #12,Writtenby:GeronimoStilton,Narratedby:BillLobely,2 hrs and 20 mins,04-08-08,English,5 out of 5 stars34 ratings,468.00
1,The Burning Maze,Writtenby:RickRiordan,Narratedby:RobbieDaymond,13 hrs and 8 mins,01-05-18,English,4.5 out of 5 stars41 ratings,820.00
2,The Deep End,Writtenby:JeffKinney,Narratedby:DanRussell,2 hrs and 3 mins,06-11-20,English,4.5 out of 5 stars38 ratings,410.00
3,Daughter of the Deep,Writtenby:RickRiordan,Narratedby:SoneelaNankani,11 hrs and 16 mins,05-10-21,English,4.5 out of 5 stars12 ratings,615.00
4,"The Lightning Thief: Percy Jackson, Book 1",Writtenby:RickRiordan,Narratedby:JesseBernstein,10 hrs,13-01-10,English,4.5 out of 5 stars181 ratings,820.00
...,...,...,...,...,...,...,...,...
87484,Last Days of the Bus Club,Writtenby:ChrisStewart,Narratedby:ChrisStewart,7 hrs and 34 mins,09-03-17,English,Not rated yet,596.00
87485,The Alps,Writtenby:StephenO'Shea,Narratedby:RobertFass,10 hrs and 7 mins,21-02-17,English,Not rated yet,820.00
87486,The Innocents Abroad,Writtenby:MarkTwain,Narratedby:FloGibson,19 hrs and 4 mins,30-12-16,English,Not rated yet,938.00
87487,A Sentimental Journey,Writtenby:LaurenceSterne,Narratedby:AntonLesser,4 hrs and 8 mins,23-02-11,English,Not rated yet,680.00
87488,Havana,Writtenby:MarkKurlansky,Narratedby:FleetCooper,6 hrs and 1 min,07-03-17,English,Not rated yet,569.00

In [274]:
# Remove any duplicates from the dataset
df = df.drop_duplicates()
df

,name,author,narrator,time,releasedate,language,stars,price
0,Geronimo Stilton #11 & #12,Writtenby:GeronimoStilton,Narratedby:BillLobely,2 hrs and 20 mins,04-08-08,English,5 out of 5 stars34 ratings,468.00
1,The Burning Maze,Writtenby:RickRiordan,Narratedby:RobbieDaymond,13 hrs and 8 mins,01-05-18,English,4.5 out of 5 stars41 ratings,820.00
2,The Deep End,Writtenby:JeffKinney,Narratedby:DanRussell,2 hrs and 3 mins,06-11-20,English,4.5 out of 5 stars38 ratings,410.00
3,Daughter of the Deep,Writtenby:RickRiordan,Narratedby:SoneelaNankani,11 hrs and 16 mins,05-10-21,English,4.5 out of 5 stars12 ratings,615.00
4,"The Lightning Thief: Percy Jackson, Book 1",Writtenby:RickRiordan,Narratedby:JesseBernstein,10 hrs,13-01-10,English,4.5 out of 5 stars181 ratings,820.00
...,...,...,...,...,...,...,...,...
87484,Last Days of the Bus Club,Writtenby:ChrisStewart,Narratedby:ChrisStewart,7 hrs and 34 mins,09-03-17,English,Not rated yet,596.00
87485,The Alps,Writtenby:StephenO'Shea,Narratedby:RobertFass,10 hrs and 7 mins,21-02-17,English,Not rated yet,820.00
87486,The Innocents Abroad,Writtenby:MarkTwain,Narratedby:FloGibson,19 hrs and 4 mins,30-12-16,English,Not rated yet,938.00
87487,A Sentimental Journey,Writtenby:LaurenceSterne,Narratedby:AntonLesser,4 hrs and 8 mins,23-02-11,English,Not rated yet,680.00
87488,Havana,Writtenby:MarkKurlansky,Narratedby:FleetCooper,6 hrs and 1 min,07-03-17,English,Not rated yet,569.00

In [275]:
# Remove extraneous strings in author column
df['author'] = df['author'].str.lstrip('Writtenby:')
df

,name,author,narrator,time,releasedate,language,stars,price
0,Geronimo Stilton #11 & #12,GeronimoStilton,Narratedby:BillLobely,2 hrs and 20 mins,04-08-08,English,5 out of 5 stars34 ratings,468.00
1,The Burning Maze,RickRiordan,Narratedby:RobbieDaymond,13 hrs and 8 mins,01-05-18,English,4.5 out of 5 stars41 ratings,820.00
2,The Deep End,JeffKinney,Narratedby:DanRussell,2 hrs and 3 mins,06-11-20,English,4.5 out of 5 stars38 ratings,410.00
3,Daughter of the Deep,RickRiordan,Narratedby:SoneelaNankani,11 hrs and 16 mins,05-10-21,English,4.5 out of 5 stars12 ratings,615.00
4,"The Lightning Thief: Percy Jackson, Book 1",RickRiordan,Narratedby:JesseBernstein,10 hrs,13-01-10,English,4.5 out of 5 stars181 ratings,820.00
...,...,...,...,...,...,...,...,...
87484,Last Days of the Bus Club,ChrisStewart,Narratedby:ChrisStewart,7 hrs and 34 mins,09-03-17,English,Not rated yet,596.00
87485,The Alps,StephenO'Shea,Narratedby:RobertFass,10 hrs and 7 mins,21-02-17,English,Not rated yet,820.00
87486,The Innocents Abroad,MarkTwain,Narratedby:FloGibson,19 hrs and 4 mins,30-12-16,English,Not rated yet,938.00
87487,A Sentimental Journey,LaurenceSterne,Narratedby:AntonLesser,4 hrs and 8 mins,23-02-11,English,Not rated yet,680.00
87488,Havana,MarkKurlansky,Narratedby:FleetCooper,6 hrs and 1 min,07-03-17,English,Not rated yet,569.00

In [276]:
# Add a space between author first and last name
df['author'] = df['author'].str.replace(r"(?<=[a-z])(?=[A-Z])", " ",regex=True)
df

,name,author,narrator,time,releasedate,language,stars,price
0,Geronimo Stilton #11 & #12,Geronimo Stilton,Narratedby:BillLobely,2 hrs and 20 mins,04-08-08,English,5 out of 5 stars34 ratings,468.00
1,The Burning Maze,Rick Riordan,Narratedby:RobbieDaymond,13 hrs and 8 mins,01-05-18,English,4.5 out of 5 stars41 ratings,820.00
2,The Deep End,Jeff Kinney,Narratedby:DanRussell,2 hrs and 3 mins,06-11-20,English,4.5 out of 5 stars38 ratings,410.00
3,Daughter of the Deep,Rick Riordan,Narratedby:SoneelaNankani,11 hrs and 16 mins,05-10-21,English,4.5 out of 5 stars12 ratings,615.00
4,"The Lightning Thief: Percy Jackson, Book 1",Rick Riordan,Narratedby:JesseBernstein,10 hrs,13-01-10,English,4.5 out of 5 stars181 ratings,820.00
...,...,...,...,...,...,...,...,...
87484,Last Days of the Bus Club,Chris Stewart,Narratedby:ChrisStewart,7 hrs and 34 mins,09-03-17,English,Not rated yet,596.00
87485,The Alps,Stephen O'Shea,Narratedby:RobertFass,10 hrs and 7 mins,21-02-17,English,Not rated yet,820.00
87486,The Innocents Abroad,Mark Twain,Narratedby:FloGibson,19 hrs and 4 mins,30-12-16,English,Not rated yet,938.00
87487,A Sentimental Journey,Laurence Sterne,Narratedby:AntonLesser,4 hrs and 8 mins,23-02-11,English,Not rated yet,680.00
87488,Havana,Mark Kurlansky,Narratedby:FleetCooper,6 hrs and 1 min,07-03-17,English,Not rated yet,569.00

In [277]:
# Remove extraneous strings in narrator column
df['narrator'] = df['narrator'].str.lstrip('Narratedby:')
df

,name,author,narrator,time,releasedate,language,stars,price
0,Geronimo Stilton #11 & #12,Geronimo Stilton,BillLobely,2 hrs and 20 mins,04-08-08,English,5 out of 5 stars34 ratings,468.00
1,The Burning Maze,Rick Riordan,RobbieDaymond,13 hrs and 8 mins,01-05-18,English,4.5 out of 5 stars41 ratings,820.00
2,The Deep End,Jeff Kinney,DanRussell,2 hrs and 3 mins,06-11-20,English,4.5 out of 5 stars38 ratings,410.00
3,Daughter of the Deep,Rick Riordan,SoneelaNankani,11 hrs and 16 mins,05-10-21,English,4.5 out of 5 stars12 ratings,615.00
4,"The Lightning Thief: Percy Jackson, Book 1",Rick Riordan,JesseBernstein,10 hrs,13-01-10,English,4.5 out of 5 stars181 ratings,820.00
...,...,...,...,...,...,...,...,...
87484,Last Days of the Bus Club,Chris Stewart,ChrisStewart,7 hrs and 34 mins,09-03-17,English,Not rated yet,596.00
87485,The Alps,Stephen O'Shea,RobertFass,10 hrs and 7 mins,21-02-17,English,Not rated yet,820.00
87486,The Innocents Abroad,Mark Twain,FloGibson,19 hrs and 4 mins,30-12-16,English,Not rated yet,938.00
87487,A Sentimental Journey,Laurence Sterne,AntonLesser,4 hrs and 8 mins,23-02-11,English,Not rated yet,680.00
87488,Havana,Mark Kurlansky,FleetCooper,6 hrs and 1 min,07-03-17,English,Not rated yet,569.00

In [278]:
# Add a space between narrator first and last name
df['narrator'] = df['narrator'].str.replace(r"(?<=[a-z])(?=[A-Z])", " ",regex=True)
df

,name,author,narrator,time,releasedate,language,stars,price
0,Geronimo Stilton #11 & #12,Geronimo Stilton,Bill Lobely,2 hrs and 20 mins,04-08-08,English,5 out of 5 stars34 ratings,468.00
1,The Burning Maze,Rick Riordan,Robbie Daymond,13 hrs and 8 mins,01-05-18,English,4.5 out of 5 stars41 ratings,820.00
2,The Deep End,Jeff Kinney,Dan Russell,2 hrs and 3 mins,06-11-20,English,4.5 out of 5 stars38 ratings,410.00
3,Daughter of the Deep,Rick Riordan,Soneela Nankani,11 hrs and 16 mins,05-10-21,English,4.5 out of 5 stars12 ratings,615.00
4,"The Lightning Thief: Percy Jackson, Book 1",Rick Riordan,Jesse Bernstein,10 hrs,13-01-10,English,4.5 out of 5 stars181 ratings,820.00
...,...,...,...,...,...,...,...,...
87484,Last Days of the Bus Club,Chris Stewart,Chris Stewart,7 hrs and 34 mins,09-03-17,English,Not rated yet,596.00
87485,The Alps,Stephen O'Shea,Robert Fass,10 hrs and 7 mins,21-02-17,English,Not rated yet,820.00
87486,The Innocents Abroad,Mark Twain,Flo Gibson,19 hrs and 4 mins,30-12-16,English,Not rated yet,938.00
87487,A Sentimental Journey,Laurence Sterne,Anton Lesser,4 hrs and 8 mins,23-02-11,English,Not rated yet,680.00
87488,Havana,Mark Kurlansky,Fleet Cooper,6 hrs and 1 min,07-03-17,English,Not rated yet,569.00

In [279]:
# Extract star rating from stars column and convert it to a float
df['star_rating'] = df['stars'].str.extract(r'(\d+\.\d+|\d+)').astype('float')
df

,name,author,narrator,time,releasedate,language,stars,price,star_rating
0,Geronimo Stilton #11 & #12,Geronimo Stilton,Bill Lobely,2 hrs and 20 mins,04-08-08,English,5 out of 5 stars34 ratings,468.00,5.0
1,The Burning Maze,Rick Riordan,Robbie Daymond,13 hrs and 8 mins,01-05-18,English,4.5 out of 5 stars41 ratings,820.00,4.5
2,The Deep End,Jeff Kinney,Dan Russell,2 hrs and 3 mins,06-11-20,English,4.5 out of 5 stars38 ratings,410.00,4.5
3,Daughter of the Deep,Rick Riordan,Soneela Nankani,11 hrs and 16 mins,05-10-21,English,4.5 out of 5 stars12 ratings,615.00,4.5
4,"The Lightning Thief: Percy Jackson, Book 1",Rick Riordan,Jesse Bernstein,10 hrs,13-01-10,English,4.5 out of 5 stars181 ratings,820.00,4.5
...,...,...,...,...,...,...,...,...,...
87484,Last Days of the Bus Club,Chris Stewart,Chris Stewart,7 hrs and 34 mins,09-03-17,English,Not rated yet,596.00,NaN
87485,The Alps,Stephen O'Shea,Robert Fass,10 hrs and 7 mins,21-02-17,English,Not rated yet,820.00,NaN
87486,The Innocents Abroad,Mark Twain,Flo Gibson,19 hrs and 4 mins,30-12-16,English,Not rated yet,938.00,NaN
87487,A Sentimental Journey,Laurence Sterne,Anton Lesser,4 hrs and 8 mins,23-02-11,English,Not rated yet,680.00,NaN
87488,Havana,Mark Kurlansky,Fleet Cooper,6 hrs and 1 min,07-03-17,English,Not rated yet,569.00,NaN

In [280]:
# Drop rows of movies that have not been rated
df = df[df['stars'] != 'Not rated yet']
df.reset_index(drop=True, inplace=True)
df

,name,author,narrator,time,releasedate,language,stars,price,star_rating
0,Geronimo Stilton #11 & #12,Geronimo Stilton,Bill Lobely,2 hrs and 20 mins,04-08-08,English,5 out of 5 stars34 ratings,468.00,5.0
1,The Burning Maze,Rick Riordan,Robbie Daymond,13 hrs and 8 mins,01-05-18,English,4.5 out of 5 stars41 ratings,820.00,4.5
2,The Deep End,Jeff Kinney,Dan Russell,2 hrs and 3 mins,06-11-20,English,4.5 out of 5 stars38 ratings,410.00,4.5
3,Daughter of the Deep,Rick Riordan,Soneela Nankani,11 hrs and 16 mins,05-10-21,English,4.5 out of 5 stars12 ratings,615.00,4.5
4,"The Lightning Thief: Percy Jackson, Book 1",Rick Riordan,Jesse Bernstein,10 hrs,13-01-10,English,4.5 out of 5 stars181 ratings,820.00,4.5
...,...,...,...,...,...,...,...,...,...
15067,Why We Fly,Evan Rail,Evan Rail,56 mins,23-06-14,English,5 out of 5 stars1 rating,100.00,5.0
15068,River Town,Peter Hessler,Peter Berkrot,14 hrs and 36 mins,04-05-10,English,5 out of 5 stars1 rating,836.00,5.0
15069,Figures in a Landscape,Paul Theroux,Edoardo Ballerini,16 hrs and 44 mins,07-06-18,English,4 out of 5 stars1 rating,949.00,4.0
15070,Tower of London,Minds,Abbey Holmes,8 mins,23-12-09,English,5 out of 5 stars1 rating,33.00,5.0
15071,Tigers in the Snow,Peter Matthiessen,George Guidall,4 hrs and 54 mins,05-08-04,English,5 out of 5 stars1 rating,702.00,5.0

In [281]:
# Drop the stars and price columns. They will not be used.
df = df.drop(columns = ['stars', 'price'])
df

,name,author,narrator,time,releasedate,language,star_rating
0,Geronimo Stilton #11 & #12,Geronimo Stilton,Bill Lobely,2 hrs and 20 mins,04-08-08,English,5.0
1,The Burning Maze,Rick Riordan,Robbie Daymond,13 hrs and 8 mins,01-05-18,English,4.5
2,The Deep End,Jeff Kinney,Dan Russell,2 hrs and 3 mins,06-11-20,English,4.5
3,Daughter of the Deep,Rick Riordan,Soneela Nankani,11 hrs and 16 mins,05-10-21,English,4.5
4,"The Lightning Thief: Percy Jackson, Book 1",Rick Riordan,Jesse Bernstein,10 hrs,13-01-10,English,4.5
...,...,...,...,...,...,...,...
15067,Why We Fly,Evan Rail,Evan Rail,56 mins,23-06-14,English,5.0
15068,River Town,Peter Hessler,Peter Berkrot,14 hrs and 36 mins,04-05-10,English,5.0
15069,Figures in a Landscape,Paul Theroux,Edoardo Ballerini,16 hrs and 44 mins,07-06-18,English,4.0
15070,Tower of London,Minds,Abbey Holmes,8 mins,23-12-09,English,5.0
15071,Tigers in the Snow,Peter Matthiessen,George Guidall,4 hrs and 54 mins,05-08-04,English,5.0

In [282]:
# Convert the releasedate column datetime format
df['releasedate'] = pd.to_datetime(df['releasedate'], format='%d-%m-%y')
df['releasedate'] = df['releasedate'].dt.strftime('%Y-%m-%d')
df

,name,author,narrator,time,releasedate,language,star_rating
0,Geronimo Stilton #11 & #12,Geronimo Stilton,Bill Lobely,2 hrs and 20 mins,2008-08-04,English,5.0
1,The Burning Maze,Rick Riordan,Robbie Daymond,13 hrs and 8 mins,2018-05-01,English,4.5
2,The Deep End,Jeff Kinney,Dan Russell,2 hrs and 3 mins,2020-11-06,English,4.5
3,Daughter of the Deep,Rick Riordan,Soneela Nankani,11 hrs and 16 mins,2021-10-05,English,4.5
4,"The Lightning Thief: Percy Jackson, Book 1",Rick Riordan,Jesse Bernstein,10 hrs,2010-01-13,English,4.5
...,...,...,...,...,...,...,...
15067,Why We Fly,Evan Rail,Evan Rail,56 mins,2014-06-23,English,5.0
15068,River Town,Peter Hessler,Peter Berkrot,14 hrs and 36 mins,2010-05-04,English,5.0
15069,Figures in a Landscape,Paul Theroux,Edoardo Ballerini,16 hrs and 44 mins,2018-06-07,English,4.0
15070,Tower of London,Minds,Abbey Holmes,8 mins,2009-12-23,English,5.0
15071,Tigers in the Snow,Peter Matthiessen,George Guidall,4 hrs and 54 mins,2004-08-05,English,5.0

In [283]:
# Extract hours and minutes as integers
hours_extracted = df['time'].str.extract(r'(\d+) hrs?')
minutes_extracted = df['time'].str.extract(r'(\d+) mins?')

# Convert hours and minutes to integers, filling NaN values with 0
df['hours'] = hours_extracted[0].fillna(0).astype(int)
df['minutes'] = minutes_extracted[0].fillna(0).astype(int)

# Calculate total time in minutes
df['total_minutes'] = df['hours'] * 60 + df['minutes']

# Convert total time in minutes to HH:MM:SS format
df['duration'] = df['total_minutes'].apply(lambda x: f"{x // 60:02d}:{x % 60:02d}:00")

# Drop intermediate and unused columns if needed
df.drop(['hours', 'minutes', 'total_minutes', 'time'], axis=1, inplace=True)
df

,name,author,narrator,releasedate,language,star_rating,duration
0,Geronimo Stilton #11 & #12,Geronimo Stilton,Bill Lobely,2008-08-04,English,5.0,02:20:00
1,The Burning Maze,Rick Riordan,Robbie Daymond,2018-05-01,English,4.5,13:08:00
2,The Deep End,Jeff Kinney,Dan Russell,2020-11-06,English,4.5,02:03:00
3,Daughter of the Deep,Rick Riordan,Soneela Nankani,2021-10-05,English,4.5,11:16:00
4,"The Lightning Thief: Percy Jackson, Book 1",Rick Riordan,Jesse Bernstein,2010-01-13,English,4.5,10:00:00
...,...,...,...,...,...,...,...
15067,Why We Fly,Evan Rail,Evan Rail,2014-06-23,English,5.0,00:56:00
15068,River Town,Peter Hessler,Peter Berkrot,2010-05-04,English,5.0,14:36:00
15069,Figures in a Landscape,Paul Theroux,Edoardo Ballerini,2018-06-07,English,4.0,16:44:00
15070,Tower of London,Minds,Abbey Holmes,2009-12-23,English,5.0,00:08:00
15071,Tigers in the Snow,Peter Matthiessen,George Guidall,2004-08-05,English,5.0,04:54:00